apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: "pr-{{ number }}"
resources:
  - ../../base
  - namespace.yaml
patches:
  - path: patch-deploy-image.yaml
    target:
      kind: Deployment
      name: node-app
