apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: pr-previews
  namespace: argocd
spec:
  generators:
  - pullRequest:
      github:
        owner: hamzaali-nxb
        repo: jenkins-test
        # repoURL: https://github.com/hamzaali-nxb/jenkins-test.git

        tokenRef:
          secretName: github-token
          key: token
      requeueAfterSeconds: 60
  template:
    metadata:
      name: "pr-{{ number }}"
    spec:
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: "pr-11"
      source:
        repoURL: https://github.com/hamzaali-nxb/jenkins-test.git
        targetRevision: "{{ head_sha }}"
        path: deploy/overlays/pr
        kustomize:
          # This lets us substitute placeholders
          # ArgoCD will replace {{ number }} in namespace and image
          namePrefix: ""
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
